[package]
name = "guild-factory"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "=1.13.6"

[dependencies.guild-sc]
path = "../guild-sc"

[dependencies.guild-sc-config]
path = "../guild-sc-config"

[dependencies.common_structs]
git = "https://github.com/TerraDharitri/drt-sc-exchange"
rev = "8ad8661"

[dependencies.utils]
git = "https://github.com/TerraDharitri/drt-sc-exchange"
rev = "8ad8661"

[dependencies.dharitri-sc-modules]
version = "=1.13.6"

[dev-dependencies]
num-bigint = "0.4"

[dev-dependencies.dharitri-sc-scenario]
version = "=1.13.6"

[dev-dependencies.farm]
git = "https://github.com/TerraDharitri/drt-sc-exchange"
rev = "8ad8661"
