[GeneralConfig]
    DelegationLegacyContractAddress = "drt1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q8vqld4"
    LKMOAStakingContractAddress     = "drt1qqqqqqqqqqqqqpgqt7tyyswqvplpcqnhwe20xqrj7q7ap27d2jpsr70pn8"
    EnergyContractAddress           = "drt1qqqqqqqqqqqqqpgqnyuph46rqr29qv5gqhyxh429zcta8r0ppr9sjfsq3s"
    ValidatorsContract              = "drt1yvesqqqqqqqqqqqqqqqqqqqqqqqqyvesqqqqqqqqqqqqqqqplllsphc9lf"


[AddressPubkeyConverter]
    #Length specifies the length in bytes of an address
    Length = 32
    # Type specifies the type of public keys: hex or bech32
    Type = "bech32"

[Reindexer]
    [Reindexer.SourceElasticSearchClient]
        Address = "http://127.0.0.1:9200"
        Username = ""
        Password = ""


[Destination]
    DestinationElasticSearchClients =  [{ Address = "http://127.0.0.1:9200", Username = "", Password = ""},
                                       { Address = "http://127.0.0.1:9211", Username = "", Password = ""}]

[APIConfig]
    URL = ""
    Username = ""
    Password = ""
