/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconDefinition } from "@fortawesome/free-solid-svg-icons";
import { CustomToastType, IComponentToast, ISimpleToast } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
import { IAccountScreenData, IConfirmScreenData, IConnectScreenData, ILedgerConnectPanelData } from "./components/functional/ledger-connect/ledger-connect.types";
import { IEventBus } from "./utils/EventBus";
import { IProviderBase, ProviderTypeEnum } from "./types/provider.types";
import { ITransactionAccount, ITransactionIconInfo, ITransactionsTableRow } from "./components/controlled/transactions-table/transactions-table.type";
import { ITransactionListItem } from "./components/visual/transaction-list-item/transaction-list-item.types";
import { IconSizeEnumType } from "./components/common/transaction-asset-icon/transaction-asset-icon.types";
import { ITransactionListItem as ITransactionListItem1 } from "./components/visual/transaction-list-item/transaction-list-item.types";
import { LocalJSX as JSX } from "@stencil/core";
import { IToastDataState, ITransactionProgressState } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
import { ITransactionValue } from "./components/controlled/transactions-table/transactions-table.type";
import { IEventBus as IEventBus1, unknown as IWalletConnectPanelData } from "./components.d";
export { IconDefinition } from "@fortawesome/free-solid-svg-icons";
export { CustomToastType, IComponentToast, ISimpleToast } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
export { IAccountScreenData, IConfirmScreenData, IConnectScreenData, ILedgerConnectPanelData } from "./components/functional/ledger-connect/ledger-connect.types";
export { IEventBus } from "./utils/EventBus";
export { IProviderBase, ProviderTypeEnum } from "./types/provider.types";
export { ITransactionAccount, ITransactionIconInfo, ITransactionsTableRow } from "./components/controlled/transactions-table/transactions-table.type";
export { ITransactionListItem } from "./components/visual/transaction-list-item/transaction-list-item.types";
export { IconSizeEnumType } from "./components/common/transaction-asset-icon/transaction-asset-icon.types";
export { ITransactionListItem as ITransactionListItem1 } from "./components/visual/transaction-list-item/transaction-list-item.types";
export { LocalJSX as JSX } from "@stencil/core";
export { IToastDataState, ITransactionProgressState } from "./components/functional/toasts-list/components/transaction-toast/transaction-toast.type";
export { ITransactionValue } from "./components/controlled/transactions-table/transactions-table.type";
export { IEventBus as IEventBus1, unknown as IWalletConnectPanelData } from "./components.d";
export namespace Components {
    interface MvxAngleLeftIcon {
        "class"?: string;
    }
    interface MvxAngleRightIcon {
        "class"?: string;
    }
    interface MvxAnglesLeftIcon {
    }
    interface MvxAnglesRightIcon {
    }
    interface MvxArrowRightIcon {
        "class"?: string;
    }
    interface MvxArrowUpRightIcon {
        "class"?: string;
    }
    interface MvxBackArrowIcon {
    }
    interface MvxCheckIcon {
        "class"?: string;
    }
    interface MvxCircleExclamationIcon {
    }
    interface MvxCloseIcon {
    }
    interface MvxCopyButton {
        "class"?: string;
        "copyIcon"?: IconDefinition | string;
        "iconClass"?: string;
        "successIcon"?: IconDefinition | string;
        "text": string;
    }
    interface MvxCustomToast {
        "toast": IComponentToast;
    }
    interface MvxDefaultTransactionIconLarge {
    }
    interface MvxDefaultTransactionIconSmall {
    }
    interface MvxDharitriLogoIcon {
        "class"?: string;
    }
    interface MvxExplorerLink {
        "class"?: string;
        "dataTestId"?: string;
        "icon"?: IconDefinition | string;
        "iconClass"?: string;
        "link": string;
        "text"?: string;
    }
    interface MvxExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface MvxFaIcon {
        "class"?: string;
        "description"?: string;
        "icon": IconDefinition | string;
    }
    interface MvxFormatAmount {
        "class"?: string;
        "dataTestId"?: string;
        "decimalClass"?: string;
        "isValid": boolean;
        "label"?: string;
        "labelClass"?: string;
        "showLabel"?: boolean;
        "valueDecimal": string;
        "valueInteger": string;
    }
    interface MvxGenericToast {
        "toast": CustomToastType;
    }
    interface MvxLedgerAddresses {
        "accountScreenData": IAccountScreenData;
        "selectedIndex": number;
    }
    interface MvxLedgerConfirm {
        "confirmScreenData": IConfirmScreenData;
    }
    interface MvxLedgerConnect {
        "data": ILedgerConnectPanelData;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface MvxLedgerIcon {
    }
    interface MvxLedgerIntro {
        "connectScreenData"?: IConnectScreenData;
        "isAwaiting"?: boolean;
    }
    interface MvxLedgerProviderIcon {
        "class"?: string;
    }
    interface MvxMagnifyingGlassIcon {
        "class"?: string;
    }
    interface MvxMetamaskProviderIcon {
        "class"?: string;
    }
    interface MvxNotificationsFeed {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface MvxPagination {
        "class"?: string;
        "currentPage": number;
        "isDisabled"?: boolean;
        "totalPages": number;
    }
    interface MvxPaginationEllipsis {
        "isActive": boolean;
    }
    interface MvxPaginationEllipsisForm {
        "isVisible": boolean;
        "maxPageToSearchFor": number;
    }
    interface MvxPasskeyProviderIcon {
        "class"?: string;
    }
    interface MvxPencilIcon {
        "class"?: string;
    }
    interface MvxPendingTransactionsPanel {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface MvxPreloader {
        "class"?: string;
    }
    interface MvxProviderIdleScreen {
        "introText": string;
        "introTitle": string;
        "provider": IProviderBase | null;
    }
    interface MvxSidePanel {
        "hasBackButton"?: boolean;
        "isOpen": boolean;
        "panelClassName"?: string;
        "panelTitle": string;
        "showHeader"?: boolean;
    }
    interface MvxSidePanelHeader {
        "hasLeftButton"?: boolean;
        "hasRightButton"?: boolean;
        "panelClassName"?: string;
        "panelTitle": string;
    }
    interface MvxSignTransactionsAdvanced {
        "data": string;
        "highlight"?: string;
    }
    interface MvxSignTransactionsFooter {
    }
    interface MvxSignTransactionsHeader {
    }
    interface MvxSignTransactionsOverview {
        "action": string;
        "amount": string;
        "identifier": string;
        "interactor": string;
        "interactorIconUrl": string;
        "isApp": boolean;
        "networkFee": string;
        "tokenIconUrl": string;
        "usdValue": string;
    }
    interface MvxSignTransactionsPanel {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface MvxSimpleToast {
        "toast": ISimpleToast;
    }
    interface MvxSpinnerIcon {
        "class"?: string;
    }
    interface MvxToastList {
        "getEventBus": () => Promise<IEventBus>;
    }
    interface MvxTooltip {
        "class"?: string;
        "position": 'top' | 'bottom';
        "trigger": HTMLElement;
        "triggerOnClick"?: boolean;
    }
    interface MvxTransactionAccount {
        "account": ITransactionAccount;
        "class"?: string;
        "dataTestId"?: string;
        "scope": 'receiver' | 'sender';
        "showLockedAccounts": boolean;
    }
    interface MvxTransactionAccountName {
        "address": string;
        "class"?: string;
        "dataTestId"?: string;
        "description": string;
        "name"?: string;
    }
    interface MvxTransactionAge {
        "age": string;
        "class"?: string;
        "tooltip"?: string;
    }
    interface MvxTransactionAssetIcon {
        "iconSize": IconSizeEnumType;
        "transaction": ITransactionListItem;
    }
    interface MvxTransactionDirectionBadge {
        "class"?: string;
        "direction": string;
    }
    interface MvxTransactionHash {
        "class"?: string;
        "transaction": ITransactionsTableRow;
    }
    interface MvxTransactionIcon {
        "class"?: string;
        "iconInfo": ITransactionIconInfo;
    }
    interface MvxTransactionListItem {
        "transaction": ITransactionListItem1;
    }
    interface MvxTransactionMethod {
        "actionDescription": string;
        "class"?: string;
        "method": string;
    }
    interface MvxTransactionShards {
        "class"?: string;
        "transaction": ITransactionsTableRow;
    }
    interface MvxTransactionToast {
        "fullWidth"?: boolean;
        "processedTransactionsStatus": string | JSX.Element;
        "toastDataState": IToastDataState;
        "toastId": string;
        "transactionProgressState"?: ITransactionProgressState;
        "transactions": ITransactionListItem[];
        "wrapperClass": string;
    }
    interface MvxTransactionToastContent {
        "fullWidth"?: boolean;
        "processedTransactionsStatus"?: string | JSX.Element;
        "toastDataState": IToastDataState;
        "transactions": ITransactionListItem[];
    }
    interface MvxTransactionToastDetails {
        "maxShownTransactions": number;
        "processedTransactionsStatus"?: string | JSX.Element;
        "transactionClass": string;
        "transactions"?: ITransactionListItem[];
    }
    interface MvxTransactionToastDetailsBody {
        "hash": string;
        "index": string;
        "link": string;
        "status"?: string;
        "transactionClass"?: string;
    }
    interface MvxTransactionToastProgress {
        "endTime"?: number;
        "startTime"?: number;
    }
    interface MvxTransactionValue {
        "class"?: string;
        "value": ITransactionValue;
    }
    interface MvxTransactionsTable {
        "class"?: string;
        "transactions": ITransactionsTableRow[];
    }
    interface MvxTriangularWarningIcon {
    }
    interface MvxTrimText {
        "class"?: string;
        "dataTestId"?: string;
        "text": string;
    }
    interface MvxUnlockButton {
        "class"?: string;
        "icon"?: HTMLElement;
        "iconUrl": string;
        "label": string;
        "type"?: IProviderBase['type'];
    }
    interface MvxUnlockPanel {
        "closeWithAnimation": () => Promise<unknown>;
        "getEventBus": () => Promise<IEventBus>;
    }
    interface MvxUnlockPanelFooter {
    }
    interface MvxUnlockPanelGroup {
        "groupTitle": string;
        "providers": IProviderBase[];
    }
    interface MvxUnlockProviderButton {
        "class"?: string;
        "provider": IProviderBase<ProviderTypeEnum>;
    }
    interface MvxWalletConnect {
        "data": IWalletConnectPanelData;
        "getEventBus": () => Promise<IEventBus>;
        "qrCodeSvg": string;
    }
    interface MvxWalletConnectDownload {
    }
    interface MvxWalletConnectScan {
        "qrCodeSvg": string;
    }
    interface MvxWalletProviderIcon {
        "class"?: string;
    }
    interface MvxXaliasProviderIcon {
    }
    interface MvxXportalDownloadQrIcon {
    }
    interface MvxXportalQrCodePreloader {
        "class"?: string;
    }
}
export interface MvxCustomToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxCustomToastElement;
}
export interface MvxGenericToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxGenericToastElement;
}
export interface MvxLedgerAddressesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxLedgerAddressesElement;
}
export interface MvxLedgerIntroCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxLedgerIntroElement;
}
export interface MvxPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxPaginationElement;
}
export interface MvxPaginationEllipsisFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxPaginationEllipsisFormElement;
}
export interface MvxProviderIdleScreenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxProviderIdleScreenElement;
}
export interface MvxSidePanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxSidePanelElement;
}
export interface MvxSidePanelHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxSidePanelHeaderElement;
}
export interface MvxSimpleToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxSimpleToastElement;
}
export interface MvxTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxTooltipElement;
}
export interface MvxTransactionToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxTransactionToastElement;
}
export interface MvxTransactionToastContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxTransactionToastContentElement;
}
export interface MvxUnlockPanelGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxUnlockPanelGroupElement;
}
export interface MvxWalletConnectScanCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMvxWalletConnectScanElement;
}
declare global {
    interface HTMLMvxAngleLeftIconElement extends Components.MvxAngleLeftIcon, HTMLStencilElement {
    }
    var HTMLMvxAngleLeftIconElement: {
        prototype: HTMLMvxAngleLeftIconElement;
        new (): HTMLMvxAngleLeftIconElement;
    };
    interface HTMLMvxAngleRightIconElement extends Components.MvxAngleRightIcon, HTMLStencilElement {
    }
    var HTMLMvxAngleRightIconElement: {
        prototype: HTMLMvxAngleRightIconElement;
        new (): HTMLMvxAngleRightIconElement;
    };
    interface HTMLMvxAnglesLeftIconElement extends Components.MvxAnglesLeftIcon, HTMLStencilElement {
    }
    var HTMLMvxAnglesLeftIconElement: {
        prototype: HTMLMvxAnglesLeftIconElement;
        new (): HTMLMvxAnglesLeftIconElement;
    };
    interface HTMLMvxAnglesRightIconElement extends Components.MvxAnglesRightIcon, HTMLStencilElement {
    }
    var HTMLMvxAnglesRightIconElement: {
        prototype: HTMLMvxAnglesRightIconElement;
        new (): HTMLMvxAnglesRightIconElement;
    };
    interface HTMLMvxArrowRightIconElement extends Components.MvxArrowRightIcon, HTMLStencilElement {
    }
    var HTMLMvxArrowRightIconElement: {
        prototype: HTMLMvxArrowRightIconElement;
        new (): HTMLMvxArrowRightIconElement;
    };
    interface HTMLMvxArrowUpRightIconElement extends Components.MvxArrowUpRightIcon, HTMLStencilElement {
    }
    var HTMLMvxArrowUpRightIconElement: {
        prototype: HTMLMvxArrowUpRightIconElement;
        new (): HTMLMvxArrowUpRightIconElement;
    };
    interface HTMLMvxBackArrowIconElement extends Components.MvxBackArrowIcon, HTMLStencilElement {
    }
    var HTMLMvxBackArrowIconElement: {
        prototype: HTMLMvxBackArrowIconElement;
        new (): HTMLMvxBackArrowIconElement;
    };
    interface HTMLMvxCheckIconElement extends Components.MvxCheckIcon, HTMLStencilElement {
    }
    var HTMLMvxCheckIconElement: {
        prototype: HTMLMvxCheckIconElement;
        new (): HTMLMvxCheckIconElement;
    };
    interface HTMLMvxCircleExclamationIconElement extends Components.MvxCircleExclamationIcon, HTMLStencilElement {
    }
    var HTMLMvxCircleExclamationIconElement: {
        prototype: HTMLMvxCircleExclamationIconElement;
        new (): HTMLMvxCircleExclamationIconElement;
    };
    interface HTMLMvxCloseIconElement extends Components.MvxCloseIcon, HTMLStencilElement {
    }
    var HTMLMvxCloseIconElement: {
        prototype: HTMLMvxCloseIconElement;
        new (): HTMLMvxCloseIconElement;
    };
    interface HTMLMvxCopyButtonElement extends Components.MvxCopyButton, HTMLStencilElement {
    }
    var HTMLMvxCopyButtonElement: {
        prototype: HTMLMvxCopyButtonElement;
        new (): HTMLMvxCopyButtonElement;
    };
    interface HTMLMvxCustomToastElementEventMap {
        "deleteToast": string;
    }
    interface HTMLMvxCustomToastElement extends Components.MvxCustomToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxCustomToastElementEventMap>(type: K, listener: (this: HTMLMvxCustomToastElement, ev: MvxCustomToastCustomEvent<HTMLMvxCustomToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxCustomToastElementEventMap>(type: K, listener: (this: HTMLMvxCustomToastElement, ev: MvxCustomToastCustomEvent<HTMLMvxCustomToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxCustomToastElement: {
        prototype: HTMLMvxCustomToastElement;
        new (): HTMLMvxCustomToastElement;
    };
    interface HTMLMvxDefaultTransactionIconLargeElement extends Components.MvxDefaultTransactionIconLarge, HTMLStencilElement {
    }
    var HTMLMvxDefaultTransactionIconLargeElement: {
        prototype: HTMLMvxDefaultTransactionIconLargeElement;
        new (): HTMLMvxDefaultTransactionIconLargeElement;
    };
    interface HTMLMvxDefaultTransactionIconSmallElement extends Components.MvxDefaultTransactionIconSmall, HTMLStencilElement {
    }
    var HTMLMvxDefaultTransactionIconSmallElement: {
        prototype: HTMLMvxDefaultTransactionIconSmallElement;
        new (): HTMLMvxDefaultTransactionIconSmallElement;
    };
    interface HTMLMvxDharitriLogoIconElement extends Components.MvxDharitriLogoIcon, HTMLStencilElement {
    }
    var HTMLMvxDharitriLogoIconElement: {
        prototype: HTMLMvxDharitriLogoIconElement;
        new (): HTMLMvxDharitriLogoIconElement;
    };
    interface HTMLMvxExplorerLinkElement extends Components.MvxExplorerLink, HTMLStencilElement {
    }
    var HTMLMvxExplorerLinkElement: {
        prototype: HTMLMvxExplorerLinkElement;
        new (): HTMLMvxExplorerLinkElement;
    };
    interface HTMLMvxExtensionProviderIconElement extends Components.MvxExtensionProviderIcon, HTMLStencilElement {
    }
    var HTMLMvxExtensionProviderIconElement: {
        prototype: HTMLMvxExtensionProviderIconElement;
        new (): HTMLMvxExtensionProviderIconElement;
    };
    interface HTMLMvxFaIconElement extends Components.MvxFaIcon, HTMLStencilElement {
    }
    var HTMLMvxFaIconElement: {
        prototype: HTMLMvxFaIconElement;
        new (): HTMLMvxFaIconElement;
    };
    interface HTMLMvxFormatAmountElement extends Components.MvxFormatAmount, HTMLStencilElement {
    }
    var HTMLMvxFormatAmountElement: {
        prototype: HTMLMvxFormatAmountElement;
        new (): HTMLMvxFormatAmountElement;
    };
    interface HTMLMvxGenericToastElementEventMap {
        "deleteToast": string;
    }
    interface HTMLMvxGenericToastElement extends Components.MvxGenericToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxGenericToastElementEventMap>(type: K, listener: (this: HTMLMvxGenericToastElement, ev: MvxGenericToastCustomEvent<HTMLMvxGenericToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxGenericToastElementEventMap>(type: K, listener: (this: HTMLMvxGenericToastElement, ev: MvxGenericToastCustomEvent<HTMLMvxGenericToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxGenericToastElement: {
        prototype: HTMLMvxGenericToastElement;
        new (): HTMLMvxGenericToastElement;
    };
    interface HTMLMvxLedgerAddressesElementEventMap {
        "accessWallet": any;
        "selectAccount": any;
        "pageChange": number;
    }
    interface HTMLMvxLedgerAddressesElement extends Components.MvxLedgerAddresses, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxLedgerAddressesElementEventMap>(type: K, listener: (this: HTMLMvxLedgerAddressesElement, ev: MvxLedgerAddressesCustomEvent<HTMLMvxLedgerAddressesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxLedgerAddressesElementEventMap>(type: K, listener: (this: HTMLMvxLedgerAddressesElement, ev: MvxLedgerAddressesCustomEvent<HTMLMvxLedgerAddressesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxLedgerAddressesElement: {
        prototype: HTMLMvxLedgerAddressesElement;
        new (): HTMLMvxLedgerAddressesElement;
    };
    interface HTMLMvxLedgerConfirmElement extends Components.MvxLedgerConfirm, HTMLStencilElement {
    }
    var HTMLMvxLedgerConfirmElement: {
        prototype: HTMLMvxLedgerConfirmElement;
        new (): HTMLMvxLedgerConfirmElement;
    };
    interface HTMLMvxLedgerConnectElement extends Components.MvxLedgerConnect, HTMLStencilElement {
    }
    var HTMLMvxLedgerConnectElement: {
        prototype: HTMLMvxLedgerConnectElement;
        new (): HTMLMvxLedgerConnectElement;
    };
    interface HTMLMvxLedgerIconElement extends Components.MvxLedgerIcon, HTMLStencilElement {
    }
    var HTMLMvxLedgerIconElement: {
        prototype: HTMLMvxLedgerIconElement;
        new (): HTMLMvxLedgerIconElement;
    };
    interface HTMLMvxLedgerIntroElementEventMap {
        "connect": any;
    }
    interface HTMLMvxLedgerIntroElement extends Components.MvxLedgerIntro, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxLedgerIntroElementEventMap>(type: K, listener: (this: HTMLMvxLedgerIntroElement, ev: MvxLedgerIntroCustomEvent<HTMLMvxLedgerIntroElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxLedgerIntroElementEventMap>(type: K, listener: (this: HTMLMvxLedgerIntroElement, ev: MvxLedgerIntroCustomEvent<HTMLMvxLedgerIntroElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxLedgerIntroElement: {
        prototype: HTMLMvxLedgerIntroElement;
        new (): HTMLMvxLedgerIntroElement;
    };
    interface HTMLMvxLedgerProviderIconElement extends Components.MvxLedgerProviderIcon, HTMLStencilElement {
    }
    var HTMLMvxLedgerProviderIconElement: {
        prototype: HTMLMvxLedgerProviderIconElement;
        new (): HTMLMvxLedgerProviderIconElement;
    };
    interface HTMLMvxMagnifyingGlassIconElement extends Components.MvxMagnifyingGlassIcon, HTMLStencilElement {
    }
    var HTMLMvxMagnifyingGlassIconElement: {
        prototype: HTMLMvxMagnifyingGlassIconElement;
        new (): HTMLMvxMagnifyingGlassIconElement;
    };
    interface HTMLMvxMetamaskProviderIconElement extends Components.MvxMetamaskProviderIcon, HTMLStencilElement {
    }
    var HTMLMvxMetamaskProviderIconElement: {
        prototype: HTMLMvxMetamaskProviderIconElement;
        new (): HTMLMvxMetamaskProviderIconElement;
    };
    interface HTMLMvxNotificationsFeedElement extends Components.MvxNotificationsFeed, HTMLStencilElement {
    }
    var HTMLMvxNotificationsFeedElement: {
        prototype: HTMLMvxNotificationsFeedElement;
        new (): HTMLMvxNotificationsFeedElement;
    };
    interface HTMLMvxPaginationElementEventMap {
        "pageChange": number;
    }
    interface HTMLMvxPaginationElement extends Components.MvxPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxPaginationElementEventMap>(type: K, listener: (this: HTMLMvxPaginationElement, ev: MvxPaginationCustomEvent<HTMLMvxPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxPaginationElementEventMap>(type: K, listener: (this: HTMLMvxPaginationElement, ev: MvxPaginationCustomEvent<HTMLMvxPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxPaginationElement: {
        prototype: HTMLMvxPaginationElement;
        new (): HTMLMvxPaginationElement;
    };
    interface HTMLMvxPaginationEllipsisElement extends Components.MvxPaginationEllipsis, HTMLStencilElement {
    }
    var HTMLMvxPaginationEllipsisElement: {
        prototype: HTMLMvxPaginationEllipsisElement;
        new (): HTMLMvxPaginationEllipsisElement;
    };
    interface HTMLMvxPaginationEllipsisFormElementEventMap {
        "search": number;
    }
    interface HTMLMvxPaginationEllipsisFormElement extends Components.MvxPaginationEllipsisForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxPaginationEllipsisFormElementEventMap>(type: K, listener: (this: HTMLMvxPaginationEllipsisFormElement, ev: MvxPaginationEllipsisFormCustomEvent<HTMLMvxPaginationEllipsisFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxPaginationEllipsisFormElementEventMap>(type: K, listener: (this: HTMLMvxPaginationEllipsisFormElement, ev: MvxPaginationEllipsisFormCustomEvent<HTMLMvxPaginationEllipsisFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxPaginationEllipsisFormElement: {
        prototype: HTMLMvxPaginationEllipsisFormElement;
        new (): HTMLMvxPaginationEllipsisFormElement;
    };
    interface HTMLMvxPasskeyProviderIconElement extends Components.MvxPasskeyProviderIcon, HTMLStencilElement {
    }
    var HTMLMvxPasskeyProviderIconElement: {
        prototype: HTMLMvxPasskeyProviderIconElement;
        new (): HTMLMvxPasskeyProviderIconElement;
    };
    interface HTMLMvxPencilIconElement extends Components.MvxPencilIcon, HTMLStencilElement {
    }
    var HTMLMvxPencilIconElement: {
        prototype: HTMLMvxPencilIconElement;
        new (): HTMLMvxPencilIconElement;
    };
    interface HTMLMvxPendingTransactionsPanelElement extends Components.MvxPendingTransactionsPanel, HTMLStencilElement {
    }
    var HTMLMvxPendingTransactionsPanelElement: {
        prototype: HTMLMvxPendingTransactionsPanelElement;
        new (): HTMLMvxPendingTransactionsPanelElement;
    };
    interface HTMLMvxPreloaderElement extends Components.MvxPreloader, HTMLStencilElement {
    }
    var HTMLMvxPreloaderElement: {
        prototype: HTMLMvxPreloaderElement;
        new (): HTMLMvxPreloaderElement;
    };
    interface HTMLMvxProviderIdleScreenElementEventMap {
        "close": any;
        "access": any;
    }
    interface HTMLMvxProviderIdleScreenElement extends Components.MvxProviderIdleScreen, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxProviderIdleScreenElementEventMap>(type: K, listener: (this: HTMLMvxProviderIdleScreenElement, ev: MvxProviderIdleScreenCustomEvent<HTMLMvxProviderIdleScreenElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxProviderIdleScreenElementEventMap>(type: K, listener: (this: HTMLMvxProviderIdleScreenElement, ev: MvxProviderIdleScreenCustomEvent<HTMLMvxProviderIdleScreenElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxProviderIdleScreenElement: {
        prototype: HTMLMvxProviderIdleScreenElement;
        new (): HTMLMvxProviderIdleScreenElement;
    };
    interface HTMLMvxSidePanelElementEventMap {
        "close": void;
        "back": void;
    }
    interface HTMLMvxSidePanelElement extends Components.MvxSidePanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxSidePanelElementEventMap>(type: K, listener: (this: HTMLMvxSidePanelElement, ev: MvxSidePanelCustomEvent<HTMLMvxSidePanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxSidePanelElementEventMap>(type: K, listener: (this: HTMLMvxSidePanelElement, ev: MvxSidePanelCustomEvent<HTMLMvxSidePanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxSidePanelElement: {
        prototype: HTMLMvxSidePanelElement;
        new (): HTMLMvxSidePanelElement;
    };
    interface HTMLMvxSidePanelHeaderElementEventMap {
        "rightButtonClick": any;
        "leftButtonClick": any;
    }
    interface HTMLMvxSidePanelHeaderElement extends Components.MvxSidePanelHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxSidePanelHeaderElementEventMap>(type: K, listener: (this: HTMLMvxSidePanelHeaderElement, ev: MvxSidePanelHeaderCustomEvent<HTMLMvxSidePanelHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxSidePanelHeaderElementEventMap>(type: K, listener: (this: HTMLMvxSidePanelHeaderElement, ev: MvxSidePanelHeaderCustomEvent<HTMLMvxSidePanelHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxSidePanelHeaderElement: {
        prototype: HTMLMvxSidePanelHeaderElement;
        new (): HTMLMvxSidePanelHeaderElement;
    };
    interface HTMLMvxSignTransactionsAdvancedElement extends Components.MvxSignTransactionsAdvanced, HTMLStencilElement {
    }
    var HTMLMvxSignTransactionsAdvancedElement: {
        prototype: HTMLMvxSignTransactionsAdvancedElement;
        new (): HTMLMvxSignTransactionsAdvancedElement;
    };
    interface HTMLMvxSignTransactionsFooterElement extends Components.MvxSignTransactionsFooter, HTMLStencilElement {
    }
    var HTMLMvxSignTransactionsFooterElement: {
        prototype: HTMLMvxSignTransactionsFooterElement;
        new (): HTMLMvxSignTransactionsFooterElement;
    };
    interface HTMLMvxSignTransactionsHeaderElement extends Components.MvxSignTransactionsHeader, HTMLStencilElement {
    }
    var HTMLMvxSignTransactionsHeaderElement: {
        prototype: HTMLMvxSignTransactionsHeaderElement;
        new (): HTMLMvxSignTransactionsHeaderElement;
    };
    interface HTMLMvxSignTransactionsOverviewElement extends Components.MvxSignTransactionsOverview, HTMLStencilElement {
    }
    var HTMLMvxSignTransactionsOverviewElement: {
        prototype: HTMLMvxSignTransactionsOverviewElement;
        new (): HTMLMvxSignTransactionsOverviewElement;
    };
    interface HTMLMvxSignTransactionsPanelElement extends Components.MvxSignTransactionsPanel, HTMLStencilElement {
    }
    var HTMLMvxSignTransactionsPanelElement: {
        prototype: HTMLMvxSignTransactionsPanelElement;
        new (): HTMLMvxSignTransactionsPanelElement;
    };
    interface HTMLMvxSimpleToastElementEventMap {
        "deleteToast": void;
    }
    interface HTMLMvxSimpleToastElement extends Components.MvxSimpleToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxSimpleToastElementEventMap>(type: K, listener: (this: HTMLMvxSimpleToastElement, ev: MvxSimpleToastCustomEvent<HTMLMvxSimpleToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxSimpleToastElementEventMap>(type: K, listener: (this: HTMLMvxSimpleToastElement, ev: MvxSimpleToastCustomEvent<HTMLMvxSimpleToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxSimpleToastElement: {
        prototype: HTMLMvxSimpleToastElement;
        new (): HTMLMvxSimpleToastElement;
    };
    interface HTMLMvxSpinnerIconElement extends Components.MvxSpinnerIcon, HTMLStencilElement {
    }
    var HTMLMvxSpinnerIconElement: {
        prototype: HTMLMvxSpinnerIconElement;
        new (): HTMLMvxSpinnerIconElement;
    };
    interface HTMLMvxToastListElement extends Components.MvxToastList, HTMLStencilElement {
    }
    var HTMLMvxToastListElement: {
        prototype: HTMLMvxToastListElement;
        new (): HTMLMvxToastListElement;
    };
    interface HTMLMvxTooltipElementEventMap {
        "triggerRender": boolean;
    }
    interface HTMLMvxTooltipElement extends Components.MvxTooltip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxTooltipElementEventMap>(type: K, listener: (this: HTMLMvxTooltipElement, ev: MvxTooltipCustomEvent<HTMLMvxTooltipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxTooltipElementEventMap>(type: K, listener: (this: HTMLMvxTooltipElement, ev: MvxTooltipCustomEvent<HTMLMvxTooltipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxTooltipElement: {
        prototype: HTMLMvxTooltipElement;
        new (): HTMLMvxTooltipElement;
    };
    interface HTMLMvxTransactionAccountElement extends Components.MvxTransactionAccount, HTMLStencilElement {
    }
    var HTMLMvxTransactionAccountElement: {
        prototype: HTMLMvxTransactionAccountElement;
        new (): HTMLMvxTransactionAccountElement;
    };
    interface HTMLMvxTransactionAccountNameElement extends Components.MvxTransactionAccountName, HTMLStencilElement {
    }
    var HTMLMvxTransactionAccountNameElement: {
        prototype: HTMLMvxTransactionAccountNameElement;
        new (): HTMLMvxTransactionAccountNameElement;
    };
    interface HTMLMvxTransactionAgeElement extends Components.MvxTransactionAge, HTMLStencilElement {
    }
    var HTMLMvxTransactionAgeElement: {
        prototype: HTMLMvxTransactionAgeElement;
        new (): HTMLMvxTransactionAgeElement;
    };
    interface HTMLMvxTransactionAssetIconElement extends Components.MvxTransactionAssetIcon, HTMLStencilElement {
    }
    var HTMLMvxTransactionAssetIconElement: {
        prototype: HTMLMvxTransactionAssetIconElement;
        new (): HTMLMvxTransactionAssetIconElement;
    };
    interface HTMLMvxTransactionDirectionBadgeElement extends Components.MvxTransactionDirectionBadge, HTMLStencilElement {
    }
    var HTMLMvxTransactionDirectionBadgeElement: {
        prototype: HTMLMvxTransactionDirectionBadgeElement;
        new (): HTMLMvxTransactionDirectionBadgeElement;
    };
    interface HTMLMvxTransactionHashElement extends Components.MvxTransactionHash, HTMLStencilElement {
    }
    var HTMLMvxTransactionHashElement: {
        prototype: HTMLMvxTransactionHashElement;
        new (): HTMLMvxTransactionHashElement;
    };
    interface HTMLMvxTransactionIconElement extends Components.MvxTransactionIcon, HTMLStencilElement {
    }
    var HTMLMvxTransactionIconElement: {
        prototype: HTMLMvxTransactionIconElement;
        new (): HTMLMvxTransactionIconElement;
    };
    interface HTMLMvxTransactionListItemElement extends Components.MvxTransactionListItem, HTMLStencilElement {
    }
    var HTMLMvxTransactionListItemElement: {
        prototype: HTMLMvxTransactionListItemElement;
        new (): HTMLMvxTransactionListItemElement;
    };
    interface HTMLMvxTransactionMethodElement extends Components.MvxTransactionMethod, HTMLStencilElement {
    }
    var HTMLMvxTransactionMethodElement: {
        prototype: HTMLMvxTransactionMethodElement;
        new (): HTMLMvxTransactionMethodElement;
    };
    interface HTMLMvxTransactionShardsElement extends Components.MvxTransactionShards, HTMLStencilElement {
    }
    var HTMLMvxTransactionShardsElement: {
        prototype: HTMLMvxTransactionShardsElement;
        new (): HTMLMvxTransactionShardsElement;
    };
    interface HTMLMvxTransactionToastElementEventMap {
        "deleteToast": void;
    }
    interface HTMLMvxTransactionToastElement extends Components.MvxTransactionToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxTransactionToastElementEventMap>(type: K, listener: (this: HTMLMvxTransactionToastElement, ev: MvxTransactionToastCustomEvent<HTMLMvxTransactionToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxTransactionToastElementEventMap>(type: K, listener: (this: HTMLMvxTransactionToastElement, ev: MvxTransactionToastCustomEvent<HTMLMvxTransactionToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxTransactionToastElement: {
        prototype: HTMLMvxTransactionToastElement;
        new (): HTMLMvxTransactionToastElement;
    };
    interface HTMLMvxTransactionToastContentElementEventMap {
        "deleteToast": void;
    }
    interface HTMLMvxTransactionToastContentElement extends Components.MvxTransactionToastContent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxTransactionToastContentElementEventMap>(type: K, listener: (this: HTMLMvxTransactionToastContentElement, ev: MvxTransactionToastContentCustomEvent<HTMLMvxTransactionToastContentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxTransactionToastContentElementEventMap>(type: K, listener: (this: HTMLMvxTransactionToastContentElement, ev: MvxTransactionToastContentCustomEvent<HTMLMvxTransactionToastContentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxTransactionToastContentElement: {
        prototype: HTMLMvxTransactionToastContentElement;
        new (): HTMLMvxTransactionToastContentElement;
    };
    interface HTMLMvxTransactionToastDetailsElement extends Components.MvxTransactionToastDetails, HTMLStencilElement {
    }
    var HTMLMvxTransactionToastDetailsElement: {
        prototype: HTMLMvxTransactionToastDetailsElement;
        new (): HTMLMvxTransactionToastDetailsElement;
    };
    interface HTMLMvxTransactionToastDetailsBodyElement extends Components.MvxTransactionToastDetailsBody, HTMLStencilElement {
    }
    var HTMLMvxTransactionToastDetailsBodyElement: {
        prototype: HTMLMvxTransactionToastDetailsBodyElement;
        new (): HTMLMvxTransactionToastDetailsBodyElement;
    };
    interface HTMLMvxTransactionToastProgressElement extends Components.MvxTransactionToastProgress, HTMLStencilElement {
    }
    var HTMLMvxTransactionToastProgressElement: {
        prototype: HTMLMvxTransactionToastProgressElement;
        new (): HTMLMvxTransactionToastProgressElement;
    };
    interface HTMLMvxTransactionValueElement extends Components.MvxTransactionValue, HTMLStencilElement {
    }
    var HTMLMvxTransactionValueElement: {
        prototype: HTMLMvxTransactionValueElement;
        new (): HTMLMvxTransactionValueElement;
    };
    interface HTMLMvxTransactionsTableElement extends Components.MvxTransactionsTable, HTMLStencilElement {
    }
    var HTMLMvxTransactionsTableElement: {
        prototype: HTMLMvxTransactionsTableElement;
        new (): HTMLMvxTransactionsTableElement;
    };
    interface HTMLMvxTriangularWarningIconElement extends Components.MvxTriangularWarningIcon, HTMLStencilElement {
    }
    var HTMLMvxTriangularWarningIconElement: {
        prototype: HTMLMvxTriangularWarningIconElement;
        new (): HTMLMvxTriangularWarningIconElement;
    };
    interface HTMLMvxTrimTextElement extends Components.MvxTrimText, HTMLStencilElement {
    }
    var HTMLMvxTrimTextElement: {
        prototype: HTMLMvxTrimTextElement;
        new (): HTMLMvxTrimTextElement;
    };
    interface HTMLMvxUnlockButtonElement extends Components.MvxUnlockButton, HTMLStencilElement {
    }
    var HTMLMvxUnlockButtonElement: {
        prototype: HTMLMvxUnlockButtonElement;
        new (): HTMLMvxUnlockButtonElement;
    };
    interface HTMLMvxUnlockPanelElement extends Components.MvxUnlockPanel, HTMLStencilElement {
    }
    var HTMLMvxUnlockPanelElement: {
        prototype: HTMLMvxUnlockPanelElement;
        new (): HTMLMvxUnlockPanelElement;
    };
    interface HTMLMvxUnlockPanelFooterElement extends Components.MvxUnlockPanelFooter, HTMLStencilElement {
    }
    var HTMLMvxUnlockPanelFooterElement: {
        prototype: HTMLMvxUnlockPanelFooterElement;
        new (): HTMLMvxUnlockPanelFooterElement;
    };
    interface HTMLMvxUnlockPanelGroupElementEventMap {
        "login": IProviderBase;
    }
    interface HTMLMvxUnlockPanelGroupElement extends Components.MvxUnlockPanelGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxUnlockPanelGroupElementEventMap>(type: K, listener: (this: HTMLMvxUnlockPanelGroupElement, ev: MvxUnlockPanelGroupCustomEvent<HTMLMvxUnlockPanelGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxUnlockPanelGroupElementEventMap>(type: K, listener: (this: HTMLMvxUnlockPanelGroupElement, ev: MvxUnlockPanelGroupCustomEvent<HTMLMvxUnlockPanelGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxUnlockPanelGroupElement: {
        prototype: HTMLMvxUnlockPanelGroupElement;
        new (): HTMLMvxUnlockPanelGroupElement;
    };
    interface HTMLMvxUnlockProviderButtonElement extends Components.MvxUnlockProviderButton, HTMLStencilElement {
    }
    var HTMLMvxUnlockProviderButtonElement: {
        prototype: HTMLMvxUnlockProviderButtonElement;
        new (): HTMLMvxUnlockProviderButtonElement;
    };
    interface HTMLMvxWalletConnectElement extends Components.MvxWalletConnect, HTMLStencilElement {
    }
    var HTMLMvxWalletConnectElement: {
        prototype: HTMLMvxWalletConnectElement;
        new (): HTMLMvxWalletConnectElement;
    };
    interface HTMLMvxWalletConnectDownloadElement extends Components.MvxWalletConnectDownload, HTMLStencilElement {
    }
    var HTMLMvxWalletConnectDownloadElement: {
        prototype: HTMLMvxWalletConnectDownloadElement;
        new (): HTMLMvxWalletConnectDownloadElement;
    };
    interface HTMLMvxWalletConnectScanElementEventMap {
        "downloadClick": any;
    }
    interface HTMLMvxWalletConnectScanElement extends Components.MvxWalletConnectScan, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMvxWalletConnectScanElementEventMap>(type: K, listener: (this: HTMLMvxWalletConnectScanElement, ev: MvxWalletConnectScanCustomEvent<HTMLMvxWalletConnectScanElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMvxWalletConnectScanElementEventMap>(type: K, listener: (this: HTMLMvxWalletConnectScanElement, ev: MvxWalletConnectScanCustomEvent<HTMLMvxWalletConnectScanElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMvxWalletConnectScanElement: {
        prototype: HTMLMvxWalletConnectScanElement;
        new (): HTMLMvxWalletConnectScanElement;
    };
    interface HTMLMvxWalletProviderIconElement extends Components.MvxWalletProviderIcon, HTMLStencilElement {
    }
    var HTMLMvxWalletProviderIconElement: {
        prototype: HTMLMvxWalletProviderIconElement;
        new (): HTMLMvxWalletProviderIconElement;
    };
    interface HTMLMvxXaliasProviderIconElement extends Components.MvxXaliasProviderIcon, HTMLStencilElement {
    }
    var HTMLMvxXaliasProviderIconElement: {
        prototype: HTMLMvxXaliasProviderIconElement;
        new (): HTMLMvxXaliasProviderIconElement;
    };
    interface HTMLMvxXportalDownloadQrIconElement extends Components.MvxXportalDownloadQrIcon, HTMLStencilElement {
    }
    var HTMLMvxXportalDownloadQrIconElement: {
        prototype: HTMLMvxXportalDownloadQrIconElement;
        new (): HTMLMvxXportalDownloadQrIconElement;
    };
    interface HTMLMvxXportalQrCodePreloaderElement extends Components.MvxXportalQrCodePreloader, HTMLStencilElement {
    }
    var HTMLMvxXportalQrCodePreloaderElement: {
        prototype: HTMLMvxXportalQrCodePreloaderElement;
        new (): HTMLMvxXportalQrCodePreloaderElement;
    };
    interface HTMLElementTagNameMap {
        "drt-angle-left-icon": HTMLMvxAngleLeftIconElement;
        "drt-angle-right-icon": HTMLMvxAngleRightIconElement;
        "drt-angles-left-icon": HTMLMvxAnglesLeftIconElement;
        "drt-angles-right-icon": HTMLMvxAnglesRightIconElement;
        "drt-arrow-right-icon": HTMLMvxArrowRightIconElement;
        "drt-arrow-up-right-icon": HTMLMvxArrowUpRightIconElement;
        "drt-back-arrow-icon": HTMLMvxBackArrowIconElement;
        "drt-check-icon": HTMLMvxCheckIconElement;
        "drt-circle-exclamation-icon": HTMLMvxCircleExclamationIconElement;
        "drt-close-icon": HTMLMvxCloseIconElement;
        "drt-copy-button": HTMLMvxCopyButtonElement;
        "drt-custom-toast": HTMLMvxCustomToastElement;
        "drt-default-transaction-icon-large": HTMLMvxDefaultTransactionIconLargeElement;
        "drt-default-transaction-icon-small": HTMLMvxDefaultTransactionIconSmallElement;
        "drt-dharitri-logo-icon": HTMLMvxDharitriLogoIconElement;
        "drt-explorer-link": HTMLMvxExplorerLinkElement;
        "drt-extension-provider-icon": HTMLMvxExtensionProviderIconElement;
        "drt-fa-icon": HTMLMvxFaIconElement;
        "drt-format-amount": HTMLMvxFormatAmountElement;
        "drt-generic-toast": HTMLMvxGenericToastElement;
        "drt-ledger-addresses": HTMLMvxLedgerAddressesElement;
        "drt-ledger-confirm": HTMLMvxLedgerConfirmElement;
        "drt-ledger-connect": HTMLMvxLedgerConnectElement;
        "drt-ledger-icon": HTMLMvxLedgerIconElement;
        "drt-ledger-intro": HTMLMvxLedgerIntroElement;
        "drt-ledger-provider-icon": HTMLMvxLedgerProviderIconElement;
        "drt-magnifying-glass-icon": HTMLMvxMagnifyingGlassIconElement;
        "drt-metamask-provider-icon": HTMLMvxMetamaskProviderIconElement;
        "drt-notifications-feed": HTMLMvxNotificationsFeedElement;
        "drt-pagination": HTMLMvxPaginationElement;
        "drt-pagination-ellipsis": HTMLMvxPaginationEllipsisElement;
        "drt-pagination-ellipsis-form": HTMLMvxPaginationEllipsisFormElement;
        "drt-passkey-provider-icon": HTMLMvxPasskeyProviderIconElement;
        "drt-pencil-icon": HTMLMvxPencilIconElement;
        "drt-pending-transactions-panel": HTMLMvxPendingTransactionsPanelElement;
        "drt-preloader": HTMLMvxPreloaderElement;
        "drt-provider-idle-screen": HTMLMvxProviderIdleScreenElement;
        "drt-side-panel": HTMLMvxSidePanelElement;
        "drt-side-panel-header": HTMLMvxSidePanelHeaderElement;
        "drt-sign-transactions-advanced": HTMLMvxSignTransactionsAdvancedElement;
        "drt-sign-transactions-footer": HTMLMvxSignTransactionsFooterElement;
        "drt-sign-transactions-header": HTMLMvxSignTransactionsHeaderElement;
        "drt-sign-transactions-overview": HTMLMvxSignTransactionsOverviewElement;
        "drt-sign-transactions-panel": HTMLMvxSignTransactionsPanelElement;
        "drt-simple-toast": HTMLMvxSimpleToastElement;
        "drt-spinner-icon": HTMLMvxSpinnerIconElement;
        "drt-toast-list": HTMLMvxToastListElement;
        "drt-tooltip": HTMLMvxTooltipElement;
        "drt-transaction-account": HTMLMvxTransactionAccountElement;
        "drt-transaction-account-name": HTMLMvxTransactionAccountNameElement;
        "drt-transaction-age": HTMLMvxTransactionAgeElement;
        "drt-transaction-asset-icon": HTMLMvxTransactionAssetIconElement;
        "drt-transaction-direction-badge": HTMLMvxTransactionDirectionBadgeElement;
        "drt-transaction-hash": HTMLMvxTransactionHashElement;
        "drt-transaction-icon": HTMLMvxTransactionIconElement;
        "drt-transaction-list-item": HTMLMvxTransactionListItemElement;
        "drt-transaction-method": HTMLMvxTransactionMethodElement;
        "drt-transaction-shards": HTMLMvxTransactionShardsElement;
        "drt-transaction-toast": HTMLMvxTransactionToastElement;
        "drt-transaction-toast-content": HTMLMvxTransactionToastContentElement;
        "drt-transaction-toast-details": HTMLMvxTransactionToastDetailsElement;
        "drt-transaction-toast-details-body": HTMLMvxTransactionToastDetailsBodyElement;
        "drt-transaction-toast-progress": HTMLMvxTransactionToastProgressElement;
        "drt-transaction-value": HTMLMvxTransactionValueElement;
        "drt-transactions-table": HTMLMvxTransactionsTableElement;
        "drt-triangular-warning-icon": HTMLMvxTriangularWarningIconElement;
        "drt-trim-text": HTMLMvxTrimTextElement;
        "drt-unlock-button": HTMLMvxUnlockButtonElement;
        "drt-unlock-panel": HTMLMvxUnlockPanelElement;
        "drt-unlock-panel-footer": HTMLMvxUnlockPanelFooterElement;
        "drt-unlock-panel-group": HTMLMvxUnlockPanelGroupElement;
        "drt-unlock-provider-button": HTMLMvxUnlockProviderButtonElement;
        "drt-wallet-connect": HTMLMvxWalletConnectElement;
        "drt-wallet-connect-download": HTMLMvxWalletConnectDownloadElement;
        "drt-wallet-connect-scan": HTMLMvxWalletConnectScanElement;
        "drt-wallet-provider-icon": HTMLMvxWalletProviderIconElement;
        "drt-xalias-provider-icon": HTMLMvxXaliasProviderIconElement;
        "drt-xportal-download-qr-icon": HTMLMvxXportalDownloadQrIconElement;
        "drt-xportal-qr-code-preloader": HTMLMvxXportalQrCodePreloaderElement;
    }
}
declare namespace LocalJSX {
    interface MvxAngleLeftIcon {
        "class"?: string;
    }
    interface MvxAngleRightIcon {
        "class"?: string;
    }
    interface MvxAnglesLeftIcon {
    }
    interface MvxAnglesRightIcon {
    }
    interface MvxArrowRightIcon {
        "class"?: string;
    }
    interface MvxArrowUpRightIcon {
        "class"?: string;
    }
    interface MvxBackArrowIcon {
    }
    interface MvxCheckIcon {
        "class"?: string;
    }
    interface MvxCircleExclamationIcon {
    }
    interface MvxCloseIcon {
    }
    interface MvxCopyButton {
        "class"?: string;
        "copyIcon"?: IconDefinition | string;
        "iconClass"?: string;
        "successIcon"?: IconDefinition | string;
        "text"?: string;
    }
    interface MvxCustomToast {
        "onDeleteToast"?: (event: MvxCustomToastCustomEvent<string>) => void;
        "toast"?: IComponentToast;
    }
    interface MvxDefaultTransactionIconLarge {
    }
    interface MvxDefaultTransactionIconSmall {
    }
    interface MvxDharitriLogoIcon {
        "class"?: string;
    }
    interface MvxExplorerLink {
        "class"?: string;
        "dataTestId"?: string;
        "icon"?: IconDefinition | string;
        "iconClass"?: string;
        "link"?: string;
        "text"?: string;
    }
    interface MvxExtensionProviderIcon {
        "class"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface MvxFaIcon {
        "class"?: string;
        "description"?: string;
        "icon"?: IconDefinition | string;
    }
    interface MvxFormatAmount {
        "class"?: string;
        "dataTestId"?: string;
        "decimalClass"?: string;
        "isValid"?: boolean;
        "label"?: string;
        "labelClass"?: string;
        "showLabel"?: boolean;
        "valueDecimal"?: string;
        "valueInteger"?: string;
    }
    interface MvxGenericToast {
        "onDeleteToast"?: (event: MvxGenericToastCustomEvent<string>) => void;
        "toast"?: CustomToastType;
    }
    interface MvxLedgerAddresses {
        "accountScreenData"?: IAccountScreenData;
        "onAccessWallet"?: (event: MvxLedgerAddressesCustomEvent<any>) => void;
        "onPageChange"?: (event: MvxLedgerAddressesCustomEvent<number>) => void;
        "onSelectAccount"?: (event: MvxLedgerAddressesCustomEvent<any>) => void;
        "selectedIndex"?: number;
    }
    interface MvxLedgerConfirm {
        "confirmScreenData"?: IConfirmScreenData;
    }
    interface MvxLedgerConnect {
        "data"?: ILedgerConnectPanelData;
    }
    interface MvxLedgerIcon {
    }
    interface MvxLedgerIntro {
        "connectScreenData"?: IConnectScreenData;
        "isAwaiting"?: boolean;
        "onConnect"?: (event: MvxLedgerIntroCustomEvent<any>) => void;
    }
    interface MvxLedgerProviderIcon {
        "class"?: string;
    }
    interface MvxMagnifyingGlassIcon {
        "class"?: string;
    }
    interface MvxMetamaskProviderIcon {
        "class"?: string;
    }
    interface MvxNotificationsFeed {
    }
    interface MvxPagination {
        "class"?: string;
        "currentPage"?: number;
        "isDisabled"?: boolean;
        "onPageChange"?: (event: MvxPaginationCustomEvent<number>) => void;
        "totalPages"?: number;
    }
    interface MvxPaginationEllipsis {
        "isActive"?: boolean;
    }
    interface MvxPaginationEllipsisForm {
        "isVisible"?: boolean;
        "maxPageToSearchFor"?: number;
        "onSearch"?: (event: MvxPaginationEllipsisFormCustomEvent<number>) => void;
    }
    interface MvxPasskeyProviderIcon {
        "class"?: string;
    }
    interface MvxPencilIcon {
        "class"?: string;
    }
    interface MvxPendingTransactionsPanel {
    }
    interface MvxPreloader {
        "class"?: string;
    }
    interface MvxProviderIdleScreen {
        "introText"?: string;
        "introTitle"?: string;
        "onAccess"?: (event: MvxProviderIdleScreenCustomEvent<any>) => void;
        "onClose"?: (event: MvxProviderIdleScreenCustomEvent<any>) => void;
        "provider"?: IProviderBase | null;
    }
    interface MvxSidePanel {
        "hasBackButton"?: boolean;
        "isOpen"?: boolean;
        "onBack"?: (event: MvxSidePanelCustomEvent<void>) => void;
        "onClose"?: (event: MvxSidePanelCustomEvent<void>) => void;
        "panelClassName"?: string;
        "panelTitle"?: string;
        "showHeader"?: boolean;
    }
    interface MvxSidePanelHeader {
        "hasLeftButton"?: boolean;
        "hasRightButton"?: boolean;
        "onLeftButtonClick"?: (event: MvxSidePanelHeaderCustomEvent<any>) => void;
        "onRightButtonClick"?: (event: MvxSidePanelHeaderCustomEvent<any>) => void;
        "panelClassName"?: string;
        "panelTitle"?: string;
    }
    interface MvxSignTransactionsAdvanced {
        "data"?: string;
        "highlight"?: string;
    }
    interface MvxSignTransactionsFooter {
    }
    interface MvxSignTransactionsHeader {
    }
    interface MvxSignTransactionsOverview {
        "action"?: string;
        "amount"?: string;
        "identifier"?: string;
        "interactor"?: string;
        "interactorIconUrl"?: string;
        "isApp"?: boolean;
        "networkFee"?: string;
        "tokenIconUrl"?: string;
        "usdValue"?: string;
    }
    interface MvxSignTransactionsPanel {
    }
    interface MvxSimpleToast {
        "onDeleteToast"?: (event: MvxSimpleToastCustomEvent<void>) => void;
        "toast"?: ISimpleToast;
    }
    interface MvxSpinnerIcon {
        "class"?: string;
    }
    interface MvxToastList {
    }
    interface MvxTooltip {
        "class"?: string;
        "onTriggerRender"?: (event: MvxTooltipCustomEvent<boolean>) => void;
        "position"?: 'top' | 'bottom';
        "trigger"?: HTMLElement;
        "triggerOnClick"?: boolean;
    }
    interface MvxTransactionAccount {
        "account"?: ITransactionAccount;
        "class"?: string;
        "dataTestId"?: string;
        "scope"?: 'receiver' | 'sender';
        "showLockedAccounts"?: boolean;
    }
    interface MvxTransactionAccountName {
        "address"?: string;
        "class"?: string;
        "dataTestId"?: string;
        "description"?: string;
        "name"?: string;
    }
    interface MvxTransactionAge {
        "age"?: string;
        "class"?: string;
        "tooltip"?: string;
    }
    interface MvxTransactionAssetIcon {
        "iconSize"?: IconSizeEnumType;
        "transaction"?: ITransactionListItem;
    }
    interface MvxTransactionDirectionBadge {
        "class"?: string;
        "direction"?: string;
    }
    interface MvxTransactionHash {
        "class"?: string;
        "transaction"?: ITransactionsTableRow;
    }
    interface MvxTransactionIcon {
        "class"?: string;
        "iconInfo"?: ITransactionIconInfo;
    }
    interface MvxTransactionListItem {
        "transaction"?: ITransactionListItem1;
    }
    interface MvxTransactionMethod {
        "actionDescription"?: string;
        "class"?: string;
        "method"?: string;
    }
    interface MvxTransactionShards {
        "class"?: string;
        "transaction"?: ITransactionsTableRow;
    }
    interface MvxTransactionToast {
        "fullWidth"?: boolean;
        "onDeleteToast"?: (event: MvxTransactionToastCustomEvent<void>) => void;
        "processedTransactionsStatus"?: string | JSX.Element;
        "toastDataState"?: IToastDataState;
        "toastId"?: string;
        "transactionProgressState"?: ITransactionProgressState;
        "transactions"?: ITransactionListItem[];
        "wrapperClass"?: string;
    }
    interface MvxTransactionToastContent {
        "fullWidth"?: boolean;
        "onDeleteToast"?: (event: MvxTransactionToastContentCustomEvent<void>) => void;
        "processedTransactionsStatus"?: string | JSX.Element;
        "toastDataState"?: IToastDataState;
        "transactions"?: ITransactionListItem[];
    }
    interface MvxTransactionToastDetails {
        "maxShownTransactions"?: number;
        "processedTransactionsStatus"?: string | JSX.Element;
        "transactionClass"?: string;
        "transactions"?: ITransactionListItem[];
    }
    interface MvxTransactionToastDetailsBody {
        "hash"?: string;
        "index"?: string;
        "link"?: string;
        "status"?: string;
        "transactionClass"?: string;
    }
    interface MvxTransactionToastProgress {
        "endTime"?: number;
        "startTime"?: number;
    }
    interface MvxTransactionValue {
        "class"?: string;
        "value"?: ITransactionValue;
    }
    interface MvxTransactionsTable {
        "class"?: string;
        "transactions"?: ITransactionsTableRow[];
    }
    interface MvxTriangularWarningIcon {
    }
    interface MvxTrimText {
        "class"?: string;
        "dataTestId"?: string;
        "text"?: string;
    }
    interface MvxUnlockButton {
        "class"?: string;
        "icon"?: HTMLElement;
        "iconUrl"?: string;
        "label"?: string;
        "type"?: IProviderBase['type'];
    }
    interface MvxUnlockPanel {
    }
    interface MvxUnlockPanelFooter {
    }
    interface MvxUnlockPanelGroup {
        "groupTitle"?: string;
        "onLogin"?: (event: MvxUnlockPanelGroupCustomEvent<IProviderBase>) => void;
        "providers"?: IProviderBase[];
    }
    interface MvxUnlockProviderButton {
        "class"?: string;
        "provider"?: IProviderBase<ProviderTypeEnum>;
    }
    interface MvxWalletConnect {
        "data"?: IWalletConnectPanelData;
        "qrCodeSvg"?: string;
    }
    interface MvxWalletConnectDownload {
    }
    interface MvxWalletConnectScan {
        "onDownloadClick"?: (event: MvxWalletConnectScanCustomEvent<any>) => void;
        "qrCodeSvg"?: string;
    }
    interface MvxWalletProviderIcon {
        "class"?: string;
    }
    interface MvxXaliasProviderIcon {
    }
    interface MvxXportalDownloadQrIcon {
    }
    interface MvxXportalQrCodePreloader {
        "class"?: string;
    }
    interface IntrinsicElements {
        "drt-angle-left-icon": MvxAngleLeftIcon;
        "drt-angle-right-icon": MvxAngleRightIcon;
        "drt-angles-left-icon": MvxAnglesLeftIcon;
        "drt-angles-right-icon": MvxAnglesRightIcon;
        "drt-arrow-right-icon": MvxArrowRightIcon;
        "drt-arrow-up-right-icon": MvxArrowUpRightIcon;
        "drt-back-arrow-icon": MvxBackArrowIcon;
        "drt-check-icon": MvxCheckIcon;
        "drt-circle-exclamation-icon": MvxCircleExclamationIcon;
        "drt-close-icon": MvxCloseIcon;
        "drt-copy-button": MvxCopyButton;
        "drt-custom-toast": MvxCustomToast;
        "drt-default-transaction-icon-large": MvxDefaultTransactionIconLarge;
        "drt-default-transaction-icon-small": MvxDefaultTransactionIconSmall;
        "drt-dharitri-logo-icon": MvxDharitriLogoIcon;
        "drt-explorer-link": MvxExplorerLink;
        "drt-extension-provider-icon": MvxExtensionProviderIcon;
        "drt-fa-icon": MvxFaIcon;
        "drt-format-amount": MvxFormatAmount;
        "drt-generic-toast": MvxGenericToast;
        "drt-ledger-addresses": MvxLedgerAddresses;
        "drt-ledger-confirm": MvxLedgerConfirm;
        "drt-ledger-connect": MvxLedgerConnect;
        "drt-ledger-icon": MvxLedgerIcon;
        "drt-ledger-intro": MvxLedgerIntro;
        "drt-ledger-provider-icon": MvxLedgerProviderIcon;
        "drt-magnifying-glass-icon": MvxMagnifyingGlassIcon;
        "drt-metamask-provider-icon": MvxMetamaskProviderIcon;
        "drt-notifications-feed": MvxNotificationsFeed;
        "drt-pagination": MvxPagination;
        "drt-pagination-ellipsis": MvxPaginationEllipsis;
        "drt-pagination-ellipsis-form": MvxPaginationEllipsisForm;
        "drt-passkey-provider-icon": MvxPasskeyProviderIcon;
        "drt-pencil-icon": MvxPencilIcon;
        "drt-pending-transactions-panel": MvxPendingTransactionsPanel;
        "drt-preloader": MvxPreloader;
        "drt-provider-idle-screen": MvxProviderIdleScreen;
        "drt-side-panel": MvxSidePanel;
        "drt-side-panel-header": MvxSidePanelHeader;
        "drt-sign-transactions-advanced": MvxSignTransactionsAdvanced;
        "drt-sign-transactions-footer": MvxSignTransactionsFooter;
        "drt-sign-transactions-header": MvxSignTransactionsHeader;
        "drt-sign-transactions-overview": MvxSignTransactionsOverview;
        "drt-sign-transactions-panel": MvxSignTransactionsPanel;
        "drt-simple-toast": MvxSimpleToast;
        "drt-spinner-icon": MvxSpinnerIcon;
        "drt-toast-list": MvxToastList;
        "drt-tooltip": MvxTooltip;
        "drt-transaction-account": MvxTransactionAccount;
        "drt-transaction-account-name": MvxTransactionAccountName;
        "drt-transaction-age": MvxTransactionAge;
        "drt-transaction-asset-icon": MvxTransactionAssetIcon;
        "drt-transaction-direction-badge": MvxTransactionDirectionBadge;
        "drt-transaction-hash": MvxTransactionHash;
        "drt-transaction-icon": MvxTransactionIcon;
        "drt-transaction-list-item": MvxTransactionListItem;
        "drt-transaction-method": MvxTransactionMethod;
        "drt-transaction-shards": MvxTransactionShards;
        "drt-transaction-toast": MvxTransactionToast;
        "drt-transaction-toast-content": MvxTransactionToastContent;
        "drt-transaction-toast-details": MvxTransactionToastDetails;
        "drt-transaction-toast-details-body": MvxTransactionToastDetailsBody;
        "drt-transaction-toast-progress": MvxTransactionToastProgress;
        "drt-transaction-value": MvxTransactionValue;
        "drt-transactions-table": MvxTransactionsTable;
        "drt-triangular-warning-icon": MvxTriangularWarningIcon;
        "drt-trim-text": MvxTrimText;
        "drt-unlock-button": MvxUnlockButton;
        "drt-unlock-panel": MvxUnlockPanel;
        "drt-unlock-panel-footer": MvxUnlockPanelFooter;
        "drt-unlock-panel-group": MvxUnlockPanelGroup;
        "drt-unlock-provider-button": MvxUnlockProviderButton;
        "drt-wallet-connect": MvxWalletConnect;
        "drt-wallet-connect-download": MvxWalletConnectDownload;
        "drt-wallet-connect-scan": MvxWalletConnectScan;
        "drt-wallet-provider-icon": MvxWalletProviderIcon;
        "drt-xalias-provider-icon": MvxXaliasProviderIcon;
        "drt-xportal-download-qr-icon": MvxXportalDownloadQrIcon;
        "drt-xportal-qr-code-preloader": MvxXportalQrCodePreloader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "drt-angle-left-icon": LocalJSX.MvxAngleLeftIcon & JSXBase.HTMLAttributes<HTMLMvxAngleLeftIconElement>;
            "drt-angle-right-icon": LocalJSX.MvxAngleRightIcon & JSXBase.HTMLAttributes<HTMLMvxAngleRightIconElement>;
            "drt-angles-left-icon": LocalJSX.MvxAnglesLeftIcon & JSXBase.HTMLAttributes<HTMLMvxAnglesLeftIconElement>;
            "drt-angles-right-icon": LocalJSX.MvxAnglesRightIcon & JSXBase.HTMLAttributes<HTMLMvxAnglesRightIconElement>;
            "drt-arrow-right-icon": LocalJSX.MvxArrowRightIcon & JSXBase.HTMLAttributes<HTMLMvxArrowRightIconElement>;
            "drt-arrow-up-right-icon": LocalJSX.MvxArrowUpRightIcon & JSXBase.HTMLAttributes<HTMLMvxArrowUpRightIconElement>;
            "drt-back-arrow-icon": LocalJSX.MvxBackArrowIcon & JSXBase.HTMLAttributes<HTMLMvxBackArrowIconElement>;
            "drt-check-icon": LocalJSX.MvxCheckIcon & JSXBase.HTMLAttributes<HTMLMvxCheckIconElement>;
            "drt-circle-exclamation-icon": LocalJSX.MvxCircleExclamationIcon & JSXBase.HTMLAttributes<HTMLMvxCircleExclamationIconElement>;
            "drt-close-icon": LocalJSX.MvxCloseIcon & JSXBase.HTMLAttributes<HTMLMvxCloseIconElement>;
            "drt-copy-button": LocalJSX.MvxCopyButton & JSXBase.HTMLAttributes<HTMLMvxCopyButtonElement>;
            "drt-custom-toast": LocalJSX.MvxCustomToast & JSXBase.HTMLAttributes<HTMLMvxCustomToastElement>;
            "drt-default-transaction-icon-large": LocalJSX.MvxDefaultTransactionIconLarge & JSXBase.HTMLAttributes<HTMLMvxDefaultTransactionIconLargeElement>;
            "drt-default-transaction-icon-small": LocalJSX.MvxDefaultTransactionIconSmall & JSXBase.HTMLAttributes<HTMLMvxDefaultTransactionIconSmallElement>;
            "drt-dharitri-logo-icon": LocalJSX.MvxDharitriLogoIcon & JSXBase.HTMLAttributes<HTMLMvxDharitriLogoIconElement>;
            "drt-explorer-link": LocalJSX.MvxExplorerLink & JSXBase.HTMLAttributes<HTMLMvxExplorerLinkElement>;
            "drt-extension-provider-icon": LocalJSX.MvxExtensionProviderIcon & JSXBase.HTMLAttributes<HTMLMvxExtensionProviderIconElement>;
            "drt-fa-icon": LocalJSX.MvxFaIcon & JSXBase.HTMLAttributes<HTMLMvxFaIconElement>;
            "drt-format-amount": LocalJSX.MvxFormatAmount & JSXBase.HTMLAttributes<HTMLMvxFormatAmountElement>;
            "drt-generic-toast": LocalJSX.MvxGenericToast & JSXBase.HTMLAttributes<HTMLMvxGenericToastElement>;
            "drt-ledger-addresses": LocalJSX.MvxLedgerAddresses & JSXBase.HTMLAttributes<HTMLMvxLedgerAddressesElement>;
            "drt-ledger-confirm": LocalJSX.MvxLedgerConfirm & JSXBase.HTMLAttributes<HTMLMvxLedgerConfirmElement>;
            "drt-ledger-connect": LocalJSX.MvxLedgerConnect & JSXBase.HTMLAttributes<HTMLMvxLedgerConnectElement>;
            "drt-ledger-icon": LocalJSX.MvxLedgerIcon & JSXBase.HTMLAttributes<HTMLMvxLedgerIconElement>;
            "drt-ledger-intro": LocalJSX.MvxLedgerIntro & JSXBase.HTMLAttributes<HTMLMvxLedgerIntroElement>;
            "drt-ledger-provider-icon": LocalJSX.MvxLedgerProviderIcon & JSXBase.HTMLAttributes<HTMLMvxLedgerProviderIconElement>;
            "drt-magnifying-glass-icon": LocalJSX.MvxMagnifyingGlassIcon & JSXBase.HTMLAttributes<HTMLMvxMagnifyingGlassIconElement>;
            "drt-metamask-provider-icon": LocalJSX.MvxMetamaskProviderIcon & JSXBase.HTMLAttributes<HTMLMvxMetamaskProviderIconElement>;
            "drt-notifications-feed": LocalJSX.MvxNotificationsFeed & JSXBase.HTMLAttributes<HTMLMvxNotificationsFeedElement>;
            "drt-pagination": LocalJSX.MvxPagination & JSXBase.HTMLAttributes<HTMLMvxPaginationElement>;
            "drt-pagination-ellipsis": LocalJSX.MvxPaginationEllipsis & JSXBase.HTMLAttributes<HTMLMvxPaginationEllipsisElement>;
            "drt-pagination-ellipsis-form": LocalJSX.MvxPaginationEllipsisForm & JSXBase.HTMLAttributes<HTMLMvxPaginationEllipsisFormElement>;
            "drt-passkey-provider-icon": LocalJSX.MvxPasskeyProviderIcon & JSXBase.HTMLAttributes<HTMLMvxPasskeyProviderIconElement>;
            "drt-pencil-icon": LocalJSX.MvxPencilIcon & JSXBase.HTMLAttributes<HTMLMvxPencilIconElement>;
            "drt-pending-transactions-panel": LocalJSX.MvxPendingTransactionsPanel & JSXBase.HTMLAttributes<HTMLMvxPendingTransactionsPanelElement>;
            "drt-preloader": LocalJSX.MvxPreloader & JSXBase.HTMLAttributes<HTMLMvxPreloaderElement>;
            "drt-provider-idle-screen": LocalJSX.MvxProviderIdleScreen & JSXBase.HTMLAttributes<HTMLMvxProviderIdleScreenElement>;
            "drt-side-panel": LocalJSX.MvxSidePanel & JSXBase.HTMLAttributes<HTMLMvxSidePanelElement>;
            "drt-side-panel-header": LocalJSX.MvxSidePanelHeader & JSXBase.HTMLAttributes<HTMLMvxSidePanelHeaderElement>;
            "drt-sign-transactions-advanced": LocalJSX.MvxSignTransactionsAdvanced & JSXBase.HTMLAttributes<HTMLMvxSignTransactionsAdvancedElement>;
            "drt-sign-transactions-footer": LocalJSX.MvxSignTransactionsFooter & JSXBase.HTMLAttributes<HTMLMvxSignTransactionsFooterElement>;
            "drt-sign-transactions-header": LocalJSX.MvxSignTransactionsHeader & JSXBase.HTMLAttributes<HTMLMvxSignTransactionsHeaderElement>;
            "drt-sign-transactions-overview": LocalJSX.MvxSignTransactionsOverview & JSXBase.HTMLAttributes<HTMLMvxSignTransactionsOverviewElement>;
            "drt-sign-transactions-panel": LocalJSX.MvxSignTransactionsPanel & JSXBase.HTMLAttributes<HTMLMvxSignTransactionsPanelElement>;
            "drt-simple-toast": LocalJSX.MvxSimpleToast & JSXBase.HTMLAttributes<HTMLMvxSimpleToastElement>;
            "drt-spinner-icon": LocalJSX.MvxSpinnerIcon & JSXBase.HTMLAttributes<HTMLMvxSpinnerIconElement>;
            "drt-toast-list": LocalJSX.MvxToastList & JSXBase.HTMLAttributes<HTMLMvxToastListElement>;
            "drt-tooltip": LocalJSX.MvxTooltip & JSXBase.HTMLAttributes<HTMLMvxTooltipElement>;
            "drt-transaction-account": LocalJSX.MvxTransactionAccount & JSXBase.HTMLAttributes<HTMLMvxTransactionAccountElement>;
            "drt-transaction-account-name": LocalJSX.MvxTransactionAccountName & JSXBase.HTMLAttributes<HTMLMvxTransactionAccountNameElement>;
            "drt-transaction-age": LocalJSX.MvxTransactionAge & JSXBase.HTMLAttributes<HTMLMvxTransactionAgeElement>;
            "drt-transaction-asset-icon": LocalJSX.MvxTransactionAssetIcon & JSXBase.HTMLAttributes<HTMLMvxTransactionAssetIconElement>;
            "drt-transaction-direction-badge": LocalJSX.MvxTransactionDirectionBadge & JSXBase.HTMLAttributes<HTMLMvxTransactionDirectionBadgeElement>;
            "drt-transaction-hash": LocalJSX.MvxTransactionHash & JSXBase.HTMLAttributes<HTMLMvxTransactionHashElement>;
            "drt-transaction-icon": LocalJSX.MvxTransactionIcon & JSXBase.HTMLAttributes<HTMLMvxTransactionIconElement>;
            "drt-transaction-list-item": LocalJSX.MvxTransactionListItem & JSXBase.HTMLAttributes<HTMLMvxTransactionListItemElement>;
            "drt-transaction-method": LocalJSX.MvxTransactionMethod & JSXBase.HTMLAttributes<HTMLMvxTransactionMethodElement>;
            "drt-transaction-shards": LocalJSX.MvxTransactionShards & JSXBase.HTMLAttributes<HTMLMvxTransactionShardsElement>;
            "drt-transaction-toast": LocalJSX.MvxTransactionToast & JSXBase.HTMLAttributes<HTMLMvxTransactionToastElement>;
            "drt-transaction-toast-content": LocalJSX.MvxTransactionToastContent & JSXBase.HTMLAttributes<HTMLMvxTransactionToastContentElement>;
            "drt-transaction-toast-details": LocalJSX.MvxTransactionToastDetails & JSXBase.HTMLAttributes<HTMLMvxTransactionToastDetailsElement>;
            "drt-transaction-toast-details-body": LocalJSX.MvxTransactionToastDetailsBody & JSXBase.HTMLAttributes<HTMLMvxTransactionToastDetailsBodyElement>;
            "drt-transaction-toast-progress": LocalJSX.MvxTransactionToastProgress & JSXBase.HTMLAttributes<HTMLMvxTransactionToastProgressElement>;
            "drt-transaction-value": LocalJSX.MvxTransactionValue & JSXBase.HTMLAttributes<HTMLMvxTransactionValueElement>;
            "drt-transactions-table": LocalJSX.MvxTransactionsTable & JSXBase.HTMLAttributes<HTMLMvxTransactionsTableElement>;
            "drt-triangular-warning-icon": LocalJSX.MvxTriangularWarningIcon & JSXBase.HTMLAttributes<HTMLMvxTriangularWarningIconElement>;
            "drt-trim-text": LocalJSX.MvxTrimText & JSXBase.HTMLAttributes<HTMLMvxTrimTextElement>;
            "drt-unlock-button": LocalJSX.MvxUnlockButton & JSXBase.HTMLAttributes<HTMLMvxUnlockButtonElement>;
            "drt-unlock-panel": LocalJSX.MvxUnlockPanel & JSXBase.HTMLAttributes<HTMLMvxUnlockPanelElement>;
            "drt-unlock-panel-footer": LocalJSX.MvxUnlockPanelFooter & JSXBase.HTMLAttributes<HTMLMvxUnlockPanelFooterElement>;
            "drt-unlock-panel-group": LocalJSX.MvxUnlockPanelGroup & JSXBase.HTMLAttributes<HTMLMvxUnlockPanelGroupElement>;
            "drt-unlock-provider-button": LocalJSX.MvxUnlockProviderButton & JSXBase.HTMLAttributes<HTMLMvxUnlockProviderButtonElement>;
            "drt-wallet-connect": LocalJSX.MvxWalletConnect & JSXBase.HTMLAttributes<HTMLMvxWalletConnectElement>;
            "drt-wallet-connect-download": LocalJSX.MvxWalletConnectDownload & JSXBase.HTMLAttributes<HTMLMvxWalletConnectDownloadElement>;
            "drt-wallet-connect-scan": LocalJSX.MvxWalletConnectScan & JSXBase.HTMLAttributes<HTMLMvxWalletConnectScanElement>;
            "drt-wallet-provider-icon": LocalJSX.MvxWalletProviderIcon & JSXBase.HTMLAttributes<HTMLMvxWalletProviderIconElement>;
            "drt-xalias-provider-icon": LocalJSX.MvxXaliasProviderIcon & JSXBase.HTMLAttributes<HTMLMvxXaliasProviderIconElement>;
            "drt-xportal-download-qr-icon": LocalJSX.MvxXportalDownloadQrIcon & JSXBase.HTMLAttributes<HTMLMvxXportalDownloadQrIconElement>;
            "drt-xportal-qr-code-preloader": LocalJSX.MvxXportalQrCodePreloader & JSXBase.HTMLAttributes<HTMLMvxXportalQrCodePreloaderElement>;
        }
    }
}
