[package]
name = "metabonding"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "=0.50.5"

[dependencies.dharitri-sc-modules]
version = "=0.50.5"

[dependencies.sc_whitelist_module]
git = "https://github.com/TerraDharitri/drt-sc-exchange"
rev = "c061a85"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
hex-literal = "0.4.1"

[dev-dependencies.dharitri-sc-scenario]
version = "=0.50.5"
