[package]
name = "gas-service"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
zip = { path = "/home/dugong/Desktop/teja-work/temp/crates/zip2-2.1.1"}

[dependencies.dharitri-sc]
version = "=1.11.6"

[dev-dependencies.dharitri-sc-scenario]
version = "=1.11.6"

